// Generated by typings
// Source: https://raw.githubusercontent.com/meteor-typings/react-meteor-data/955e4521623d6574dde8e0ed1b29967ec13f2c9d/main.d.ts
declare module 'meteor/react-meteor-data' {
  import * as React from 'react';

  type ComponentConstructor<P> = React.ComponentClass<P> | React.StatelessComponent<P>

  export function createContainer<InP, D, OutP extends (InP & D)>(
    options: (props: InP) => D | {getMeteorData: (props: InP) => D, pure?: boolean},
    reactComponent: ComponentConstructor<OutP>)
    : ComponentConstructor<InP>;
}
